apiVersion: v1
kind: Service
metadata:
  name: pod-identity-webhook
  namespace: kube-system
  annotations:
    prometheus.io/port: "443"
    prometheus.io/scheme: "https"
    prometheus.io/scrape: "true"
  labels:
    application: pod-identity-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    application: pod-identity-webhook
